This material is originally made by teaching assistant [Seth Temple](sdtemple.github.io) for the course [CSE/STAT 416: Introduction to Machine Learning](https://valentina-s.github.io/cse-stat-416-sp20/). This iteration of the course happened in Spring 2020 at the University of Washington and was led by instructor Valentina Staneva.

This material is licensed under a [Creative Commons License](https://creativecommons.org/licenses/by/4.0/). Anyone, especially other educators and students, is welcome to use and modify this material with proper citation.

### Simple Example

In [ ]:
import numpy as np
from sklearn.decomposition import NMF

# data
X = np.array([[1, 1], [2, 1], [3, 1.2], [4, 1], [5, 0.8], [6, 1]])
print(X.shape) # 6 observations, 2 features

(6, 2)


In [ ]:
model = NMF(n_components=2, init='random', random_state=0)
WX = model.fit_transform(X) # returns W
HX = model.components_ # the model components are the basis column vectors

In [ ]:
print(HX.shape)
print(HX)

(2, 2)
[[2.09783018 0.30560234]
 [2.13443044 2.13171694]]


In [ ]:
print(WX.shape)
print(WX)

(6, 2)
[[0.         0.46880684]
 [0.55699523 0.3894146 ]
 [1.00331638 0.41925352]
 [1.6733999  0.22926926]
 [2.34349311 0.03927954]
 [2.78981512 0.06911798]]


In [ ]:
WX.argmax(axis=1)

array([1, 0, 0, 0, 0, 0])

In [ ]:
# matrix multiplication
print(np.matmul(WX,HX))

[[1.00063558 0.99936347]
 [1.99965977 1.00034074]
 [2.99965485 1.20034566]
 [3.9998681  1.0001321 ]
 [5.00009002 0.79990984]
 [6.00008587 0.999914  ]]


In [ ]:
print(X)

[[1.  1. ]
 [2.  1. ]
 [3.  1.2]
 [4.  1. ]
 [5.  0.8]
 [6.  1. ]]


In [ ]:
[x**2 for x in [1,2,3]]

for x in [1,2,3]:
  print (x**2)

1
4
9


In [ ]:
# first row of H
print(HX[0,:])

# ordered indices of first row of H
print(HX[0,:].argsort())
ordered_indices = HX[0,:].argsort()[::-1]
print (ordered_indices)
# highest coefficient of first row of H
print(HX[0,HX[0,:].argsort()[-1]])

values_in_first_row = [HX[0,i] for i in ordered_indices]
print (values_in_first_row)

[2.09783018 0.30560234]
[1 0]
[0 1]
2.097830183791838
[2.097830183791838, 0.30560234303173384]


In [ ]:
model.transform(X)

array([[0.        , 0.46880687],
       [0.55762104, 0.38906185],
       [1.0039665 , 0.41888706],
       [1.6736919 , 0.22910467],
       [2.3434173 , 0.03932227],
       [2.78976277, 0.06914748]])

In [ ]:
model.inverse_transform(WX)

array([[1.00063558, 0.99936347],
       [1.99965977, 1.00034074],
       [2.99965485, 1.20034566],
       [3.9998681 , 1.0001321 ],
       [5.00009002, 0.79990984],
       [6.00008587, 0.999914  ]])

In [ ]:
model.components_

array([[2.09783018, 0.30560234],
       [2.13443044, 2.13171694]])

In [ ]:
model.n_components_

2

In [ ]:
model.n_iter_

29

### Another Example

In [ ]:
# data
Y = np.array([[1, 1, 3, 5], [2, 1, 4, 8], [3, 1.2, 1.55, 0.27], [4, 1, 7.68, 3.45], [5, 0.8, .75, .5], [6, 1, 3.24, 10.9]])
print(Y.shape) # 6 observations, 4 features

(6, 4)


In [ ]:
model = NMF(n_components = 3, init = 'random', random_state = 0)
WY = model.fit_transform(Y)
HY = model.components_

/usr/local/lib/python3.8/dist-packages/sklearn/decomposition/_nmf.py:1665: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(


In [ ]:
print(WY.shape)
print(HY.shape)

(6, 3)
(3, 4)


In [ ]:
print(WY)
print(HY)

[[1.00338942 0.04872211 2.12944515 0.56569743]
 [2.2909531  0.         2.25305433 0.5824154 ]
 [0.         1.3106977  0.28242519 0.3551393 ]
 [1.57254626 1.11101224 0.         1.67211743]
 [0.23706388 2.02861284 0.         0.06037736]
 [4.1340465  1.00455239 1.38180557 0.        ]]
[[0.88127966 0.         0.72689108 2.19837154]
 [2.34295065 0.48112397 0.16331159 0.        ]
 [0.         0.37883279 0.05290644 1.31096586]
 [0.         0.31054518 3.7985735  0.        ]]


In [ ]:
# not as good
print(np.matmul(WY, HY))

[[ 0.99842019  1.00581963  2.99881634  4.99745264]
 [ 2.01897035  1.03439715  3.99682215  7.9900434 ]
 [ 3.07090003  0.8478868   1.57801697  0.37024978]
 [ 3.98889986  1.05380263  7.67617199  3.45704094]
 [ 4.96185934  0.99476417  0.73296343  0.52115448]
 [ 5.99686775  1.00678749  3.24216298 10.89967011]]


In [ ]:
print(Y)

[[ 1.    1.    3.    5.  ]
 [ 2.    1.    4.    8.  ]
 [ 3.    1.2   1.55  0.27]
 [ 4.    1.    7.68  3.45]
 [ 5.    0.8   0.75  0.5 ]
 [ 6.    1.    3.24 10.9 ]]


### Dimensions Exercise

Change `n_component` and guess at the dimensions of $\mathbf{W}$ and $\mathbf{H}$.

In [ ]:
model = NMF(n_components = 3, init = 'random', random_state = 0)
WZ = model.fit_transform(Y)
HZ = model.components_

In [ ]:
print(WZ)

[[1.14848822 0.         1.74060265]
 [1.49695266 0.10333927 2.88064583]
 [0.42842612 0.95042894 0.        ]
 [2.69933083 1.00776398 0.63915046]
 [0.         1.54282988 0.20756029]
 [0.99853856 1.15119506 4.22510604]]


In [ ]:
print(HZ)

[[0.16039008 0.28008573 2.65166913 0.70426265]
 [3.17512327 0.48301405 0.49009909 0.        ]
 [0.50726175 0.11002199 0.         2.41233104]]


In [ ]:
print(np.matmul(WZ, HZ))

[[ 1.06714725  0.51317973  3.04541076  5.00774717]
 [ 2.02945272  0.78612378  4.02006963  8.00331919]
 [ 3.08644435  0.57906657  1.60184867  0.30172451]
 [ 3.95693731  1.31312881  7.65163644  3.44288038]
 [ 5.00396246  0.7680447   0.75613952  0.50070412]
 [ 5.95857656  1.30057435  3.21199352 10.89558785]]


Selecting rank $\textit{r}$

In [ ]:
for i in range(1, 5):
  print (i)
  model = NMF(n_components = i, init = 'random', random_state = 0)
  WZ = model.fit_transform(Y)
  HZ = model.components_
  print (WZ.shape, HZ.shape, Y.shape)
  print(model.reconstruction_err_)

1
(6, 1) (1, 4) (6, 4)
8.036556669096782
2
(6, 2) (2, 4) (6, 4)
5.046854285749233
3
(6, 3) (3, 4) (6, 4)
0.939187841988581
4
(6, 4) (4, 4) (6, 4)
0.42989578979062903


/usr/local/lib/python3.8/dist-packages/sklearn/decomposition/_nmf.py:1665: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(
/usr/local/lib/python3.8/dist-packages/sklearn/decomposition/_nmf.py:1665: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(


In [ ]:
model = NMF(n_components = 4, init = 'random', random_state = 0)
WZ = model.fit_transform(Y)
HZ = model.components_
print(np.matmul(WZ, HZ))
print(Y)

[[ 0.99842019  1.00581963  2.99881634  4.99745264]
 [ 2.01897035  1.03439715  3.99682215  7.9900434 ]
 [ 3.07090003  0.8478868   1.57801697  0.37024978]
 [ 3.98889986  1.05380263  7.67617199  3.45704094]
 [ 4.96185934  0.99476417  0.73296343  0.52115448]
 [ 5.99686775  1.00678749  3.24216298 10.89967011]]
[[ 1.    1.    3.    5.  ]
 [ 2.    1.    4.    8.  ]
 [ 3.    1.2   1.55  0.27]
 [ 4.    1.    7.68  3.45]
 [ 5.    0.8   0.75  0.5 ]
 [ 6.    1.    3.24 10.9 ]]


/usr/local/lib/python3.8/dist-packages/sklearn/decomposition/_nmf.py:1665: ConvergenceWarning: Maximum number of iterations 200 reached. Increase it to improve convergence.
  warnings.warn(
